# How long in seconds will the game last, set it < 1 to disable
# default: 1200 aka 20min
gameLength: 1200

# Announce join/leave/game over messages to people not playing the game
# default: true
announceMessagesToNonPlayers: true

# Allow Hiders to see their own teams nametags as well as seekers. Seekers can never see nametags regardless.
# default: false
nametagsVisible: false

# Require bukkit permissions though a plugin to run commands, recommended on large servers
# default: true
permissionsRequired: true

# Minimum amount of players to start the game. Cannot go lower than 2.
# default: 2
minPlayers: 2

# This plugin by default functions as not tag to catch Hiders, but to pvp. All players are given weapons,
# and seekers slightly better weapons (this can be changed in items.yml). If you want, you can disable this
# entire pvp functionality, and make Hiders get found on a single hit. Hiders would also not be able to fight
# back against Seekers if disabled.
# default: true
pvp: true

# Players that join the server will automatically be placed into the lobby.
# default: false
autoJoin: false

# (When autoJoin is false), when players join the world containing the lobby, they are automatically teleported
# to the designated exit position so that they possibly don't spawn in the lobby while not in the queue. Anyone
# who ever joins in the game world (the duplicated world where the game is played) will always be teleported
# out regardless.
# default: false
teleportToExit: false

# The worldborder closes every interval, which is evey [delay] in minutes.
# Thw worldborder starts at [size], and decreases 100 blocks every interval.
# x & z are the center location. [enabled] is whenever the border is enabled.
# You can choose if Hiders are warned 30 seconds before the border moves.
worldBorder:
  x: 0
  z: 0
  delay: 10
  size: 500
  warn: true
  enabled: false

# The taunt will activate every delay set in seconds. It will spawn a firework
# on a random Hider to alert a Seeker where someone may be. You can choose
# to publicly show the taunt countdown, and have the taunt run with only
# one Hider left. Taunt delay must at least be 60s.
taunt:
  delay: 360
  whenLastPerson: false
  showCountdown: true
  enabled: true

# The glow powerup allows all Hiders to see where every Seeker is. It last for
# the amount of time set in seconds. You can allow it to be stackable, meaning
# when multiple Hiders use the powerup at the same time, it stacks the times, or
# just overwrites. Only Hiders can see that the Seekers are glowing. Delay must
# be longer than 1s.
glow:
  time: 30
  stackable: true
  enabled: true

# The message prefixes displayed before messages. The message contents themselves
# can be changed in localization.yml.
prefix:
  default: '&9Hide and Seek > &f'
  error: '&cError > &f'
  taunt: '&eTaunt > &f'
  border: '&cWorld Border > &f'
  abort: '&cAbort > &f'
  gameover: '&aGame Over > &f'
  warning: '&cWarning > &f'

# This is the section if you want a standard "waiting for players" lobby. You can specify
# the standard countdown length under [countdown] (min 10 seconds). Then once the lobby gets to a size specified
# by [changeCountdown], the timer will automatically go to 10 seconds. [min] is the minimum players
# to start the countdown. [max] is the lobby cap, set to -1 to remove maximum cap.
lobby:
  countdown: 60
  changeCountdown: 5
  min: 3
  max: 10
  enabled: true

# As a hider, the closer a seeker gets to you, the louder and faster a pining noise will play.
# There are 3 separate distances (in blocks) you can set to the 3 different levels for the noise.
# The higher the level, the closer the seeker.
seekerPing:
  distances:
    level1: 30
    level2: 20
    level3: 10
  enabled: true

# Changes the default plugin language. Currently, Supported localizations are:
# en-US (English - United States)
# de-DE (German - Germany)
locale: "en-US"

# ---------------------------------------------------------- #
# ONLY EDIT BEYOND THIS POINT IF YOU KNOW WHAT YOU ARE DOING #
# ---------------------------------------------------------- #

# The 2 coordinate bounds that will contain your hideAndSeek map. Its recommended
# that you use /hs setbounds for this, and not edit this directly, as breaking
# this section will completely break the entire plugin when you run /hs mapsave.
bounds:
  min:
    x: 0
    z: 0
  max:
    x: 0
    z: 0

# Spawn locations where players are teleported
spawns:
  # Location where players are teleported into the game (/hs start)
  game:
    x: 0
    y: 0
    z: 0
    world: world
  # Location where players are teleported into the lobby (/hs join)
  lobby:
    x: 0
    y: 0
    z: 0
    world: world
  # Location where players are teleported when they exit (/hs leave)
  exit:
    x: 0
    y: 0
    z: 0
    world: world