#============================================================#
# +--------------------------------------------------------+ #
# |                 Kenshins Hide and Seek                 | #
# |                   Configuration file                   | #
# |                    by KenshinEto                       | #
# +--------------------------------------------------------+ #
#============================================================#

# How long in seconds will the game last, set it < 1 to disable
# default: 1200 aka 20min
gameLength: 1200

# Announce join/leave/game over messages to people not playing the game
# default: true
announceMessagesToNonPlayers: true

# Allow Hiders to see their own teams nametags as well as seekers. Seekers can never see nametags regardless.
# default: false
nametagsVisible: false

# Require bukkit permissions though a plugin to run commands, recommended on large servers
# default: true
permissionsRequired: true

# Minimum amount of players to start the game. Cannot go lower than 2.
# default: 2
minPlayers: 2

# This plugin by default functions as not tag to catch Hiders, but to pvp. All players are given weapons,
# and seekers slightly better weapons (this can be changed in items.yml). If you want, you can disable this
# entire pvp functionality, and make Hiders get found on a single hit. Hiders would also not be able to fight
# back against Seekers if disabled.
# default: true
pvp: true

# Players that join the server will automatically be placed into the lobby.
# default: false
autoJoin: false

# (When autoJoin is false), when players join the world containing the lobby, they are automatically teleported
# to the designated exit position so that they don't spawn in the lobby while not in the queue. Anyone
# who ever joins in the game world (the duplicated world where the game is played) will always be teleported
# out regardless.
# default: false
teleportToExit: false

# Normally when the game ends, players are set back to the lobby to play another game.
# You can disable this, and empty the lobby after the game finishes. This is like everyone
# running /hs leave at the end of the game. Players will leave either to the exit position
# or another server depending what you have `leaveType` set too.
# default: false
leaveOnEnd: false

# What do you want to happen when a player leaves the lobby. If you are running a single server, maybe you want to send
# them to the world hub. But if you are running a bungee-cord or velocity server, maybe you want to send them to the servers
# hub.
#
#   EXIT  - Sends the player to the specified exit position set by /hs setexit
#
#   PROXY - Send the player to a specified server in a bungee-cord / velocity setup.
#
# default: EXIT
leaveType: EXIT

# Ignore this setting if you aren't using the PROXY leave type method above. If you are, set this to the server you want to send
# players too.
leaveServer: hub

# The worldborder closes every interval, which is evey [delay] in minutes.
# Thw worldborder starts at [size], and decreases 100 blocks every interval.
# x & z are the center location. [enabled] is whenever the border is enabled.
# You can choose if Hiders are warned 30 seconds before the border moves.
worldBorder:
  x: 0
  z: 0
  delay: 10
  size: 500
  moveAmount: 100
  warn: true
  enabled: false

# The taunt will activate every delay set in seconds. It will spawn a firework
# on a random Hider to alert a Seeker where someone may be. You can choose
# to publicly show the taunt countdown, and have the taunt run with only
# one Hider left. Taunt delay must at least be 60s.
taunt:
  delay: 360
  whenLastPerson: false
  showCountdown: true
  enabled: true

# The glow powerup allows all Hiders to see where every Seeker is. It last for
# the amount of time set in seconds. You can allow it to be stackable, meaning
# when multiple Hiders use the powerup at the same time, it stacks the times, or
# just overwrites. Only Hiders can see that the Seekers are glowing. Delay must
# be longer than 1s. Since the glow effect wasn't added until Minecraft 1.9,
# any server running 1.8 will have this disabled regardless of the options below.
glow:
  time: 30
  stackable: true
  enabled: true

# The message prefixes displayed before messages. The message contents themselves
# can be changed in localization.yml.
prefix:
  default: '&9Hide and Seek > &f'
  error: '&cError > &f'
  taunt: '&eTaunt > &f'
  border: '&cWorld Border > &f'
  abort: '&cAbort > &f'
  gameover: '&aGame Over > &f'
  warning: '&cWarning > &f'

# This is the section if you want a standard "waiting for players" lobby. You can specify
# the standard countdown length under [countdown] (min 10 seconds). Then once the lobby gets to a size specified
# by [changeCountdown], the timer will automatically go to 10 seconds. [min] is the minimum players
# to start the countdown. [max] is the lobby cap, set to -1 to remove maximum cap.
lobby:
  countdown: 60
  changeCountdown: 5
  min: 3
  max: 10
  enabled: true

# Below are the two items given to you when you join a lobby. A item to click to leave the lobby, and another
# to start the game. Each of these items can be toggled separately, but only these items are currently supported.
# You can customize the material, name, lore, and position of the item. And finally, the start item is marked as
# adminOnly be default since the /hs start command is also admin by default. If you set adminOnly to false, only
# the item will become non admin only, not the command.
lobbyItems:
  leave:
    material: BED
    name: "&cLeave Lobby"
    lore: ["Go back to server hub"]
    position: 8
    enabled: true
  start:
    material: CLOCK
    name: "&bStart Game"
    lore: []
    position: 0
    enabled: true
    adminOnly: true

# As a hider, the closer a seeker gets to you, the louder and faster a pining noise will play.
# There are 3 separate distances (in blocks) you can set to the 3 different levels for the noise.
# The higher the level, the closer the seeker.
seekerPing:
  distances:
    level1: 30
    level2: 20
    level3: 10
  enabled: true

# Changes the default plugin language. Currently, Supported localizations are:
# en-US (English - United States)
# de-DE (German - Germany)
locale: "en-US"

# Stop commands being run by any user while playing the game.
# Can be usefull If you aren't using a permission plugin and want
# to op people, but still want to block certain commands.
# Not really usefully if using permission plugins.
# You can add /kill for any use, but it's already blocked on those
# playing the game.
blockedCommands: [msg, tp, gamemode, kill, give, effect]

# Stop interactions with any block by any user while playing the game.
# If your map has things such as chests for aesthetic only, you can
# block the use of clicking them. It shouldn't matter what version of
# the block ID you enter, as the plugin will automatically switch to the
# block ID of your current Minecraft server version.
blockedInteracts: [FURNACE, CRAFTING_TABLE, ANVIL, CHEST, BARREL]
# ---------------------------------------------------------- #
# ONLY EDIT BEYOND THIS POINT IF YOU KNOW WHAT YOU ARE DOING #
# ---------------------------------------------------------- #

# The 2 coordinate bounds that will contain your hideAndSeek map. Its recommended
# that you use /hs setbounds for this, and not edit this directly, as breaking
# this section will completely break the entire plugin when you run /hs savemap.
bounds:
  min:
    x: 0
    z: 0
  max:
    x: 0
    z: 0

# Spawn locations where players are teleported
spawns:
  # Location where players are teleported into the game (/hs start)
  game:
    x: 0
    y: 0
    z: 0
    world: world
  # Location where players are teleported into the lobby (/hs join)
  lobby:
    x: 0
    y: 0
    z: 0
    world: world
  # Location where players are teleported when they exit (/hs leave)
  exit:
    x: 0
    y: 0
    z: 0
    world: world