name: HideAndSeek
main: net.tylermurphy.hideAndSeek.Main
version: 1.3.0
author: KenshinEto
load: STARTUP
api-version: 1.17
depend: [ProtocolLib]
commands:
  hideandseek:
    description: Hide and Seek command
    usage: /hideandseek [about|help|start|stop|setspawn|setseeker]
    aliases: hs
permissions:
  hideandseek.*:
    description: Gives access to all hideandseek commands
    children:
      hideandseek.about: true
      hideandseek.help: true
      hideandseek.reload: true
      hideandseek.setborder: true
      hideandseek.setspawn: true
      hideandseek.start: true
      hideandseek.stop: true
  hideandseek.about:
    description: Allows you to run the about command
    default: true
  hideandseek.help:
    description: Allows you to run the help command
    default: true
  hideandseek.reload:
    description: Allows you to reload the config
    default: op
  hideandseek.setborder:
    description: Allows you to set the game worldborder
    default: op
  hideandseek.setspawn:
    description: Allows you to set the game spawn point
    default: op
  hideandseek.start:
    description: Allows you to start the game
    default: op
  hideandseek.stop:
    description: Allows you to stop the game
    default: op
  hideandseek.blockbypass:
    description: Allows you to bypass the block break prevention
    default: op
