name: HideAndSeek
main: net.tylermurphy.hideAndSeek.Main
version: 1.3.3
author: KenshinEto
load: STARTUP
api-version: 1.14
depend: [ProtocolLib]
commands:
  hideandseek:
    description: Hide and Seek command
    usage: /hideandseek [command]
    aliases: hs
permissions:
  hideandseek.*:
    description: Gives access to all hideandseek commands
    children:
      hideandseek.about: true
      hideandseek.help: true
      hideandseek.reload: true
      hideandseek.setborder: true
      hideandseek.setspawn: true
      hideandseek.setlobby: true
      hideandseek.setexit: true
      hideadnseek.setbounds: true
      hideandseek.setup: true
      hideandseek.start: true
      hideandseek.stop: true
      hideandseek.savemap: true
      hideandseek.join: true
      hideandseek.leave: true
      hideandseek.leavebounds: true
  hideandseek.about:
    description: Allows you to run the about command
    default: true
  hideandseek.help:
    description: Allows you to run the help command
    default: true
  hideandseek.reload:
    description: Allows you to reload the config
    default: op
  hideandseek.setborder:
    description: Allows you to set the game worldborder
    default: op
  hideandseek.setspawn:
    description: Allows you to set the game spawn point
    default: op
  hideandseek.setlobby:
    description: Allows you to set the game lobby point
    default: op
  hideandseek.setexit:
    description: Allows you to set the game exit point
    default: op
  hideandseek.setbounds:
    description: Allows you to set bounds for the game map
    default: op
  hideandseek.setup:
    description: Allows you to see what needs to be setup for the plugin to function
    default: op
  hideandseek.start:
    description: Allows you to start the game
    default: op
  hideandseek.stop:
    description: Allows you to stop the game
    default: op
  hideandseek.savemap:
    description: Allows you to set the current game map
    default: op
  hideandseek.join:
    description: Allows you to join the game manual lobby
    default: true
  hideandseek.leave:
    description: Allows you to leave the game manual lobby
    default: true
  hideandseek.leavebounds:
    description: Allows players to leave specified game bounderies
    default: op
